ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-alpine

WORKDIR /var/www/zhyliakovv/frontend

COPY package*.json ./
RUN npm install

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]
