ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-alpine AS builder

WORKDIR /var/www/zhyliakovv/frontend

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:${NODE_VERSION}-alpine
RUN npm install -g serve
WORKDIR /app
COPY --from=builder /var/www/zhyliakovv/frontend/dist ./dist
