parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\RuntimeConstraintExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Services\Google\GoogleCalendarService:
        arguments:
            $serviceAccountPath: '%env(resolve:GOOGLE_SERVICE_ACCOUNT_PATH)%'
            $calendarId:         '%env(GOOGLE_CALENDAR_ID)%'
